### ISSUE TITLE
How about predefining styles for some languages?

### ISSUE THREAD

**Issue by Aditya94A** [akshay-naik/TextHighlighter#5]
Wouldn't it be better if the library provided out of the box styling for the most popular languages? This way every developer wouldn't have to do it manually. 

Perhaps we could take some inspiration (for the color schemes) from some of the popular prettify themes such as these: https://jmblog.github.io/color-themes-for-google-code-prettify/ or just do the popular ones like Obsidian/Monokai/Solarize

**Comment by nakshay** [comment]
Indeed this can be done, in fact this is an great idea and  the reason I have hosted TextHighlighter on Github. I will work on it  also Pull request is always welcome :)
